# Numpy

## Array

In [1]:
import numpy as np

In [2]:
# Creating Array

a = np.array([1, 2, 3])

a

array([1, 2, 3])

In [6]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [7]:
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [8]:
np.arange(4)

array([0, 1, 2, 3])

In [9]:
np.arange(3, 20)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [10]:
np.arange(3, 20, 2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [11]:
# Add, Remove, Sort

In [12]:
arrayAwal = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
arrayAwal

array([1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
arrayBaru = np.append(arrayAwal, [1, 2, 3])

In [16]:
arrayBaru

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3])

In [19]:
arrayBaru = np.delete(arrayBaru, 3)

In [20]:
arrayBaru

array([1, 2, 3, 5, 6, 7, 8, 1, 2, 3])

In [21]:
np.sort(arrayBaru)

array([1, 1, 2, 2, 3, 3, 5, 6, 7, 8])

In [22]:
arrayBaru

array([1, 2, 3, 5, 6, 7, 8, 1, 2, 3])

In [23]:
np.delete(arrayBaru, (3, 5))

array([1, 2, 3, 6, 8, 1, 2, 3])

In [24]:
# Shape and Size

In [25]:
contohArray = np.array([[[0, 1, 2, 3],
                        [4, 5, 6, 7]],
                       [[0, 1, 2, 3],
                        [4, 5, 6, 7]],
                       [[0, 1, 2, 3],
                        [4, 5, 6, 7]]])

In [26]:
contohArray

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [27]:
contohArray.ndim

3

In [28]:
contohArray.size

24

In [29]:
contohArray.shape

(3, 2, 4)

In [30]:
# Reshape

In [31]:
a = np.arange(6)

a

array([0, 1, 2, 3, 4, 5])

In [32]:
b = a.reshape(3, 2)

b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [33]:
b.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [34]:
b.reshape(1, 6)

array([[0, 1, 2, 3, 4, 5]])

In [35]:
b.reshape(6, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [36]:
# Convert 1D to 2D

a

array([0, 1, 2, 3, 4, 5])

In [38]:
b = a[np.newaxis]

In [39]:
b.shape

(1, 6)

In [40]:
a[np.newaxis, :]

array([[0, 1, 2, 3, 4, 5]])

In [41]:
a[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [43]:
a

array([0, 1, 2, 3, 4, 5])

In [44]:
np.expand_dims(a, axis=1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [45]:
np.expand_dims(a, axis=0)

array([[0, 1, 2, 3, 4, 5]])

In [46]:
# Indexing and Slicing

In [47]:
data = np.array([1, 2, 3])

In [48]:
print(data)

[1 2 3]


In [49]:
data[0]

1

In [50]:
data[1]

2

In [51]:
data[-1]

3

In [52]:
data[1:]

array([2, 3])

In [53]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [54]:
a[a>=5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [55]:
a[(a > 2) & (a < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
# Creating Array from Existing Data

In [58]:
arrayBaru

array([1, 2, 3, 5, 6, 7, 8, 1, 2, 3])

In [59]:
arrayBaru2 = arrayBaru[3:8]

In [60]:
arrayBaru2

array([5, 6, 7, 8, 1])

In [61]:
a_1 = np.array([[1, 1], [2, 2]])
a_2 = np.array([[3, 3], [4, 4]])

print(a_1)
print(a_2)

[[1 1]
 [2 2]]
[[3 3]
 [4 4]]


In [62]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [63]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [64]:
arrayBaru

array([1, 2, 3, 5, 6, 7, 8, 1, 2, 3])

In [65]:
arrayBaru3 = arrayBaru.view()

In [66]:
arrayBaru4 = arrayBaru.copy()

In [67]:
print(arrayBaru3)
print(arrayBaru4)

[1 2 3 5 6 7 8 1 2 3]
[1 2 3 5 6 7 8 1 2 3]


In [68]:
# Basic Array Operations

In [69]:
data = np.array([1, 2])
ones = np.ones(2)

In [70]:
print(data)
print(ones)

[1 2]
[1. 1.]


In [71]:
data + ones

array([2., 3.])

In [72]:
data * ones

array([1., 2.])

In [73]:
arrayBaru.sum()

38

In [74]:
a_1

array([[1, 1],
       [2, 2]])

In [75]:
a_1.sum()

6

In [76]:
a_1.sum(axis=0)

array([3, 3])

In [77]:
a_1.sum(axis=1)

array([2, 4])

In [78]:
data * 1.6

array([1.6, 3.2])

In [79]:
arrayBaru

array([1, 2, 3, 5, 6, 7, 8, 1, 2, 3])

In [80]:
arrayBaru.min()

1

In [81]:
arrayBaru.max()

8

In [82]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [83]:
a.max()

12

In [84]:
a.max(axis=0)

array([ 9, 10, 11, 12])

In [85]:
a.max(axis=1)

array([ 4,  8, 12])

## Matrices

In [86]:
# Creating Matrices

In [87]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [89]:
np.ones(3)

array([1., 1., 1.])

In [90]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [92]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [93]:
np.random.random((3, 2))

array([[0.02016622, 0.43071587],
       [0.92158271, 0.77970975],
       [0.430124  , 0.86965956]])

In [94]:
# Matrix Arithmetic

In [97]:
data = np.array([[1, 2], [3, 4]])
data

array([[1, 2],
       [3, 4]])

In [98]:
ones = np.ones([2, 2])
ones

array([[1., 1.],
       [1., 1.]])

In [99]:
data + ones

array([[2., 3.],
       [4., 5.]])

In [100]:
data * ones

array([[1., 2.],
       [3., 4.]])

In [101]:
data + arrayBaru

ValueError: operands could not be broadcast together with shapes (2,2) (10,) 

In [102]:
# Dot Product

In [103]:
a_1 = np.array([[1,2,3], [4,5,6]])
a_2 = np.array([[7,8], [9,10], [11, 12]])

np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [104]:
# Matrix Indexing

In [105]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)

[[1 2]
 [3 4]
 [5 6]]


In [106]:
data[0]

array([1, 2])

In [107]:
data[1]

array([3, 4])

In [108]:
data[2]

array([5, 6])

In [109]:
data[0, 1]

2

In [110]:
data[1, 1]

4

In [111]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [112]:
data[0:2, 1]

array([2, 4])

In [113]:
# Matrix Aggr

In [114]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [115]:
data.max()

6

In [116]:
# Transpose and Reshape

In [117]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [118]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [119]:
data.shape

(3, 2)

In [120]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [121]:
# N Dimensional Array

In [122]:
np.array([[[1,2], [3,4]],
         [[5,6], [7,8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [123]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [124]:
np.zeros((4, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [125]:
arrflat = np.zeros((4, 3))

In [126]:
arrflat.flatten()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [128]:
a = np.ones(5)

In [129]:
a.shape

(5,)

In [130]:
a # rank - 1 Array

array([1., 1., 1., 1., 1.])

In [131]:
a.T

array([1., 1., 1., 1., 1.])

In [132]:
np.dot(a, a.T)

5.0

In [135]:
a = np.ones((5, 1))

In [136]:
a.shape

(5, 1)

In [137]:
a.T

array([[1., 1., 1., 1., 1.]])

In [138]:
a

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [139]:
np.dot(a, a.T)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [140]:
np.ones((1, 5))

array([[1., 1., 1., 1., 1.]])